The ``101-lazy_matrix_mul`` module
=================================

Using ``lazy_matrix_mul``
------------------------

Import the function:

    >>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

Basic multiplication:

    >>> lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]])
    array([[ 7, 10],
           [15, 22]])

    >>> lazy_matrix_mul([[1, 2]], [[3, 4], [5, 6]])
    array([[13, 16]])

    >>> list1 = [[1, 4, 7], [2, 5, 8], [3, 6, 9]]
    >>> list2 = [[1, -1, 2], [2, -1, 2], [3, -3, 0]]
    >>> lazy_matrix_mul(list1, list2)
    array([[30, -26,  10],
           [36, -31,  14],
           [42, -36,  18]])

    >>> lazy_matrix_mul([[1, 5, 7]], [[3], [5], [8]])
    array([[84]])

Error cases:

    >>> lazy_matrix_mul(None, None)
    Traceback (most recent call last):
    TypeError: Object arrays are not currently supported

    >>> lazy_matrix_mul([[]], [[1, 2]])
    Traceback (most recent call last):
    ValueError: shapes (1,0) and (1,2) not aligned: 0 (dim 1) != 1 (dim 0)

    >>> lazy_matrix_mul([[1, 2]], [])
    Traceback (most recent call last):
    ValueError: shapes (1,2) and (0,) not aligned: 2 (dim 1) != 0 (dim 0)

    >>> lazy_matrix_mul([[1, "string"]], [[3, 4], [5, 6]])
    Traceback (most recent call last):
    TypeError: invalid data type for einsum

    >>> lazy_matrix_mul([[1, 2, 3]], [[1, 2], [3, 4]])
    Traceback (most recent call last):
    ValueError: shapes (1,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

Missing arguments:

    >>> lazy_matrix_mul([[1, 2]])
    Traceback (most recent call last):
    TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'

    >>> lazy_matrix_mul()
    Traceback (most recent call last):
    TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b' 